jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000


spring:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: iro

  config:
    import: file:.env[.properties]

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true

  minio:
    endpoint: http://localhost:9000
    username: ${MINIO_USER}
    password: ${MINIO_PASSWORD}
    bucket-name: files
