jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

spring:
  application:
    name: iro

  config:
    import: file:.env[.properties]

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true

