spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://postgres_db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  minio:
    endpoint: http://minio:9000
    username: ${MINIO_USER}
    password: ${MINIO_PASSWORD}
    bucket-name: files

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000